algoritmo "Média"
// Função : Calcular a média dos números fornecidos pelo usuário.
// Autor : Julia Ribeiro
// Data : 28/02/2023
// Seção de Declarações
var
n1,n2,n3,calculo:real

inicio
escreva ("Prezado usuário, informe o número 1:")
leia (n1)
escreva ("Prezado usuário, informe o número 2:")
leia (n2)
escreva ("Prezado usuário, informe o número 2:")
leia (n3)
calculo<- n1+n2+n3/3
escreva("O resultado da media é:", calculo)
// Seção de Comandos
fimalgoritmo
