algoritmo "Nome e Idade"
// Função :  Pedir o nome e a idade do usuário e, posteriormente, exibir uma mensagem com essas informações.
// Autor :  Julia Ribeiro
// Data : 28/02/2023
// Seção de Declarações
var
nome: caractere
idade : inteiro
inicio
escreva ("Prezado usúario, qual o seu nome?:")
leia (nome)
escreva ("Prezado usúario, informe a idade:")
leia (idade)

escreva ("Seu nome é", " ", nome, " ", "e você tem", idade, " ", "anos.")
