algoritmo "Retângulo"
// Função :  Calcular a área de um retângulo.
// Autor : Julia Ribeiro
// Data : 04/03/2023
// Seção de Declarações

var
base,altura, calculo,area: real
inicio
escreva ("Presado usuário, informe a base do seu retâgulo:")
leia(base)
escreva ("Presado usuário, informe a altura do seu retâgulo:")
leia(altura)
calculo<- base * altura
escreva ("A área do seu circulo é de:", calculo)
leia(calculo)

// Seção de Comandos
fimalgoritmo

inicio
// Seção de Comandos
fimalgoritmo
