algoritmo "Raio"
// Função : Calcular a área de um círculo.
// Autor : Julia Ribeiro
// Data : 04/03/2023
// Seção de Declarações 

var
raio, calculo,area: real
inicio
escreva ("Presado usuário, informe o raio do seu círculo:")
leia(raio)
calculo<- 3.14 * raio * raio
escreva ("A área do seu circulo é de:", calculo)
leia(calculo)

// Seção de Comandos
fimalgoritmo

inicio
// Seção de Comandos 
fimalgoritmo
